version: '3.8'

services:
  nats:
    image: nats:2.10-alpine
    container_name: fpaas-nats
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    command:
      - "-m"
      - "8222"
    restart: unless-stopped
    volumes:
      - nats_data:/data
    healthcheck:
      test: ["CMD", "nats", "server", "check", "connection"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  nats_data: