services:
  nats:
    image: nats:2.10-alpine
    container_name: fpaas-nats
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    command:
      - "-c"
      - "/etc/nats/nats.conf"
    restart: unless-stopped
    volumes:
      - ./nats.conf:/etc/nats/nats.conf:ro
      - nats_jetstream_data:/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8222/varz"]
      interval: 10s
      timeout: 5s
      retries: 3

  nats-exporter:
    image: natsio/prometheus-nats-exporter:latest
    container_name: fpaas-nats-exporter
    ports:
      - "7777:7777"
    command:
      - "-varz"
      - "-jsz=all"
      - "http://nats:8222"
    depends_on:
      - nats
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: fpaas-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--storage.tsdb.retention.time=200h"
      - "--web.enable-lifecycle"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: fpaas-grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped

  shuffler:
    build:
      context: .
      dockerfile: cmd/shuffler/Dockerfile
    container_name: fpaas-shuffler
    ports:
      - "8080:8080"
    depends_on:
      nats:
        condition: service_healthy
    environment:
      RELAY_HOST: wss://bsky.network
      NATS_URL: nats://nats:4222
      LOG_LEVEL: info
    restart: unless-stopped

  consumer:
    build:
      context: .
      dockerfile: cmd/consumer/Dockerfile
    container_name: fpaas-consumer
    ports:
      - "8082:8082"
    depends_on:
      nats:
        condition: service_healthy
    environment:
      NATS_URL: nats://nats:4222
      CONSUMER_COUNT: 100
      POLL_INTERVAL_SECONDS: 60
      BATCH_SIZE: 100
      LOG_LEVEL: info
    restart: unless-stopped

volumes:
  nats_jetstream_data:
  prometheus_data:
  grafana_data:
