global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nats'
    static_configs:
      - targets: ['nats-exporter:7777']

  - job_name: 'shuffler'
    static_configs:
      - targets: ['shuffler:8080']

  - job_name: 'webhook-receiver'
    static_configs:
      - targets: ['webhook-receiver:8090']