{
 "title": "NATS JetStream Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Streams",
   "type": "gauge",
   "description": "Shows the total number of streams configured in JetStream",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jetstream_server_total_streams" }
   ]
  },
  {
   "title": "Total Consumers",
   "type": "gauge",
   "description": "Shows the total number of consumers configured in JetStream",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jetstream_server_total_consumers"
    }
   ]
  },
  {
   "title": "JetStream Storage Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jetstream_server_total_message_bytes",
     "legendFormat": "Total Message Bytes"
    }
   ]
  },
  {
   "title": "JetStream Message Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "jetstream_server_total_messages",
     "legendFormat": "Total Messages"
    }
   ]
  }
 ]
}